### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Zedmightbedead** [chipolux/disrev#2]
Is this entirely abandoned? I tried getting it to work for an hour or two, couldn't figure it out. I don't really know python, but this seems to be the only tool left for dishonored2 and it doesn't really work without an existing understanding, and the original forums for modding Dishonored 2 are gone.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by chipolux** [comment]
Deleted that strange comment from a user that got banned.

I've not really abandoned it, just busy with other things in life and would like to get back to making this more of a usable tool eventually.

The python scripts here are really just auxiliary stuff, to actually use this you will need to install [Qt](https://www.qt.io/download-open-source), and then you should be able to build and run the project by opening `voidtweak/voidtweak/CMakeLists.txt` in Qt Creator.

You'll probably need to familiarize yourself with C++ and Qt, how to use Qt Creator, etc. Or try your luck with my `win64.bat` build script.

The tool itself, once running, will let you extract assets, modify them, and re-inject them back into Dishonored 2, and DotO. You just need to understand the formats of the assets, I only have tooling built for very few of them.

If you do end up building it, or adding any features I'd be very happy to get any PRs!
